# Generated by Django 4.1.4 on 2023-01-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playzone_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playzonegame',
            old_name='img_profile',
            new_name='game_image',
        ),
    ]
